/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Admin Starter API
 * Full-stack admin boilerplate API with AI-powered email drafting.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from './custom-fetch';
export interface DraftEmailResponse {
  subject: string;
  body: string;
}

export type ErrorResponseDetails = {[key: string]: unknown};

export interface ErrorResponse {
  error: string;
  details?: ErrorResponseDetails;
}

export interface DraftEmailRequest {
  /** @minLength 1 */
  recipientName: string;
  /** @minLength 1 */
  company: string;
  /** @minLength 1 */
  jobTitle: string;
  /** @minLength 1 */
  industry: string;
  context?: string;
}

export type GetHealth200 = {
  status: string;
};

/**
 * Returns the current health status of the API.
 * @summary Health check
 */
export const getHealth = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetHealth200>(
      {url: `/health`, method: 'GET', signal
    },
      );
    }
  



export const getGetHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }

    
export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = unknown


export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health check
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Uses AI to generate a personalized B2B cold outreach email based on lead information.
 * @summary Draft a cold outreach email
 */
export const postApiAiDraftEmail = (
    draftEmailRequest: DraftEmailRequest,
 signal?: AbortSignal
) => {
      
      
      return customFetch<DraftEmailResponse>(
      {url: `/api/ai/draft-email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: draftEmailRequest, signal
    },
      );
    }
  


export const getPostApiAiDraftEmailMutationOptions = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAiDraftEmail>>, TError,{data: DraftEmailRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAiDraftEmail>>, TError,{data: DraftEmailRequest}, TContext> => {

const mutationKey = ['postApiAiDraftEmail'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAiDraftEmail>>, {data: DraftEmailRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAiDraftEmail(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAiDraftEmailMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAiDraftEmail>>>
    export type PostApiAiDraftEmailMutationBody = DraftEmailRequest
    export type PostApiAiDraftEmailMutationError = ErrorResponse | ErrorResponse

    /**
 * @summary Draft a cold outreach email
 */
export const usePostApiAiDraftEmail = <TError = ErrorResponse | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAiDraftEmail>>, TError,{data: DraftEmailRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAiDraftEmail>>,
        TError,
        {data: DraftEmailRequest},
        TContext
      > => {

      const mutationOptions = getPostApiAiDraftEmailMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
